---
name: "Bug Report"
description: "Report an issue in the web app"
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Describe the issue you encountered"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue"
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Attach screenshots if applicable"

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      description: "Select the browser you encountered the issue on"
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant information or logs"
