---
name: "Feature Request"
description: "Suggest a new feature or enhancement"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature you would like to see implemented"
    validations:
      required: true
  
  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: "Explain why this feature would be useful and how it should work"
  
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Describe any alternative solutions or workarounds you've thought about"
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant information or screenshots"